"""Added last_updated field to packagetable.

Revision ID: 1ee0bb1d34f9
Revises: 
Create Date: 2019-10-29 14:43:25.259938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee0bb1d34f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column(
        'last_updated', sa.DATETIME(), nullable=True))
    op.create_index(op.f('ix_packages_last_updated'),
                    'packages', ['last_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_last_updated'), table_name='packages')
    op.drop_column('packages', 'last_updated')
    # ### end Alembic commands ###
