"""Created audit model class.

Revision ID: 34c973384173
Revises: 1ee0bb1d34f9
Create Date: 2019-10-30 12:34:35.582072

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '34c973384173'
down_revision = '1ee0bb1d34f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditing',
                    sa.Column('id', sa.String(), nullable=False),
                    sa.Column('created_date', sa.DateTime(), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_auditing_created_date'), 'auditing',
                    ['created_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auditing_created_date'), table_name='auditing')
    op.drop_table('auditing')
    # ### end Alembic commands ###
